# disparity computing method type
# sgbm: 0
# bm: 1
disparity_computing_method: 1

# standard2/imu_process_mode range: [0,3]
# 0 - none process, 1 - temperature process, 2 - scale and assembly process, 3 - both
imu_process_mode: 0

enable_left_rect: false
enable_right_rect: false
enable_disparity: false
enable_disparity_norm: false
enable_points: false
enable_depth: false